//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckBoxForEx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category5
    {
        public int CatId { get; set; }
        public string CategoryName { get; set; }
        public bool isselected { get; set; }
    }
    public class CategoryList
    {
        public List<Category5> categorylist { get; set; }
    }
}
