//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registration.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblRegistration
    {

        public int Id { get; set; }

        
        public string FirstName { get; set; }

        [Required(ErrorMessage ="LastName Required")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Password Required")]
        public string Password { get; set; }

        public string City { get; set; }
    }
}
